version: '3.8'

services:
  # todo-frontend
  front:
    image: todo-frontend
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: ./todo-frontend/Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./ #:/usr/src/app/todo-frontend-dev # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: todo-frontend # This will name the container
  # todo-backend
  back:
    image: todo-backend 
    build:
      context: .
      dockerfile: ./todo-backend/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./ #:/usr/src/app/todo-backend-dev
    environment:
      - REDIS_URL redis://redis:6379
      - MONGO_URL mongodb://the_username:the_password@mongo:3456/the_database
    container_name: todo-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server