version: '3.8'

services:
  server:
    image: todo-backend-dev 
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - REDIS_URL redis://redis:6379
      - MONGO_URL mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-backend-dev
