version: '3.8'            # Version 3.8 is quite new and should work

services:
  ex12_6:                    # The name of the service, can be anything
    image: todo-backend # Declares which image to use
    build:               # Declares where to build if image is not found
      context: .
      dockerfile: Dockerfile
    ports:                # Declares the ports to publish
      - 3001:3000
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - REDIS_URL redis://redis:6379
      - MONGO_URL mongodb://the_username:the_password@mongo:27017/the_database
    container-name: todo-backend